[project]
name = "sage"
version = "0.1.0"
description = "CLI coding assistant"
dependencies = [
    "google-generativeai>=0.3.0",
    "typer>=0.9.0",
    "rich>=13.0.0"
]

[project.scripts]
sage = "sage.cli:app"
