common_ignores = [
        "# Common build and dependency directories",
        "node_modules/",
        "__pycache__/",
        ".pytest_cache/",
        "target/",
        "build/",
        "dist/",
        "bin/",
        "obj/",
        ".git/",
        ".svn/",
        "",
        "# Dependency files",
        "package-lock.json",
        "yarn.lock",
        "Pipfile.lock",
        "poetry.lock",
        "",
        "# Environment and config files",
        ".env",
        ".venv/",
        "venv/",
        "env/",
        ".idea/",
        ".vscode/",
        "",
        "# OS generated files",
        ".DS_Store",
        "Thumbs.db",
        "",
        "# Logs and databases",
        "*.log",
        "*.sqlite",
        "*.db",
        "",
        "# Compiled files",
        "*.pyc",
        "*.class",
        "*.so",
        "*.dll",
        "",
        "# Sage specific - don't scan Sage folder itself",
        "Sage/"
    ]